import { View,StyleSheet,Text} from "react-native";
export default function St () {
  return (
    <View style={styles.board}>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
      <View style={styles.bl1}></View>
      <View style={styles.bl}></View>
    </View>
  )
}
const styles = StyleSheet.create(
  {
    board: {
      display:"flex",
      width: 550,
      height: 550,
      backgroundColor: "grey",
      flexDirection: "row",
      flexWrap: "wrap"
    },
    bl: {
      width: 50,
      height: 50,
      backgroundColor: "black",
      flexDirection: "column-reverse"
    },
    bl1: {
      width: 50,
      height: 50,
      backgroundColor: "white",
      flexDirection: "row-reverse"
    },
  }
)